- type: gameMapPool
  id: DefaultMapPool
  maps:
    - CorvaxGelta # MB
    - CorvaxDelta
    - CorvaxAvrite
    - CorvaxSilly
    - CorvaxAstra
    - CorvaxMaus
    - CorvaxPaper
    - CorvaxPilgrim
    - CorvaxTerra
    - CorvaxPearl
    - CorvaxTushkan
    - Amber
    - Bagel
    - Box
    - Cog
    - Core
    - Fland
    - Marathon
    - Meta
    - Oasis
    - Omega
    - Packed
    - Reach
  #- Train
